#e-jago:
#  mail:
#    server:
#      host: 10.0.15.0
#port: 587
#      username: ejago@e-jago.ml
#      sender: catalog@e-jago.ml

# datasource:
#   url: jdbc:mysql://localhost:3306/${CATALOG_DB_NAME:catalog}
#   username: ${CATALOG_DB_USER:root}
#   password: ${CATALOG_DB_PASSWORD:}
#   driver-class-name: com.mysql.cj.jdbc.Driver

# jpa:
#   hibernate:
#     ddl-auto: none
#   show-sql: false

# profiles:
#   active: ${COMPUTER_TYPE:}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${CATALOG_DB_NAME:catalog}
    username: ${CATALOG_DB_USER:root}
    password: ${CATALOG_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  #profiles:
  #  active: ${COMPUTER_TYPE:}
  #include: ${COMPUTER_TYPE:}
