spring:
  application:
    name: e-jago-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgresql:5432/dev
    username: dev
    password: dev
    hikari:
      poolName: Hikari

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080