spring:
  application:
    name: jago-auth
  datasource:
    url: jdbc:mysql://localhost:3306/jango_auth
    password: passer123
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true